### ISSUE TITLE
can you explain the mechanic with one line? XD

### ISSUE THREAD

**Issue by zzz6519003** [tinyfeng/graphql_preloader#1]

**Comment by tinyfeng** [comment]
Do you want to know the principle or function?

**Comment by zzz6519003** [comment]
principle

**Comment by tinyfeng** [comment]
我看你是马鞍山的，我就讲中文了。
原理是通过请求的json node树和项目里active record之间所属的关系，找出相同的部分并保留下来，自动includes。

**Comment by zzz6519003** [comment]
> 我看你是马鞍山的，我就讲中文了。
> 原理是通过请求的json node树和项目里active record之间所属的关系，找出相同的部分并保留下来，自动includes。

有空面基XD
